### ISSUE TITLE
Stuck on 5.

### ISSUE THREAD

**Issue by mcb-11561** [stackbit-themes/azimuth-nextjs-sanity#2]
> Copy site schemas to created sanity project
> 
> cp -R sanity-export/schemas sanity

I'm working on Windows command line. Pretty newb developing skills : stuck here though

Any insight?

**Comment by smnh** [comment]
I think in windows, the copy command is `copy` rather than `cp`. Although I am not sure what is the specified for recursive copying.
I suggest using window’s UI to copy these files.

**Comment by mcb-11561** [comment]
Cool, thx

**Comment by TomasBankauskas** [comment]
I will close this issue as no further activity occurs.
