### ISSUE TITLE
Windows - react-script-tag

### ISSUE THREAD

**Issue by richardkeller411** [stackbit-themes/azimuth-nextjs-sanity#4]
react-script-tag 

Module not found: Can't resolve 'babel-runtime/helpers/classCallCheck' in 'D:\Dev\azimuth-nextjs-sanity\node_modules\react-script-tag\lib'
{ Error: Cannot find module 'babel-runtime/helpers/extends'

Consider Script load with something else?  GGScript??

**Comment by smnh** [comment]
@richardkeller411, this issue can be solved by adding babel-runtime
```
npm install babel-runtime
```

I will update the repo

**Comment by TomasBankauskas** [comment]
I will close this issue as no further activity occurs.
